# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xbalRhuMeRsu347MqPdV19atLf2PVxH9
"""

#Recursion(factorial)

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print("Factorial of 5:", factorial(5))

# Function to calculate sum of squares
def sum_of_squares(num_list):
    total = 0
    for num in num_list:
        total += num ** 2
    return total

print("Sum of Squares:", sum_of_squares(numbers))

# Function to filter even numbers
def filter_even(num_list):
    even_list = []
    for num in num_list:
        if num % 2 == 0:
            even_list.append(num)
    return even_list

print("Even Numbers:", filter_even(numbers))

# Remove duplicates
cleaned_data = list(set(data))
print("Data after removing duplicates:", cleaned_data)

# Filter values greater than 25
filtered_data = [value for value in cleaned_data if value > 25]
print("Filtered Data (>25):", filtered_data)