# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xbalRhuMeRsu347MqPdV19atLf2PVxH9
"""

# Week 4

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample dataset
data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6],
    'Marks': [50, 55, 65, 70, 80, 90],
    'Sleep_Hours': [7, 6, 8, 5, 7, 6]
}

df = pd.DataFrame(data)

# Matplotlib
plt.figure()
plt.plot(df['Hours_Studied'], df['Marks'])
plt.title("Hours Studied vs Marks")
plt.xlabel("Hours Studied")
plt.ylabel("Marks")
plt.show()

#Seaborn
plt.figure()
sns.scatterplot(x='Hours_Studied', y='Marks', data=df)
plt.title("Scatter Plot")
plt.show()

# Histogram
plt.figure()
sns.histplot(df['Marks'])
plt.title("Marks Distribution")
plt.show()

# Heatmap
plt.figure()
corr = df.corr()
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()