# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xbalRhuMeRsu347MqPdV19atLf2PVxH9
"""

import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Basic operations
print("Mean:", np.mean(arr))
print("Square:", arr ** 2)

# Broadcasting
arr2 = arr + 10
print("Broadcasting (+10):", arr2)

# Panda Ops
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Marks': [80, 90, None, 70],
    'Age': [20, 21, 19, 22]
}

df = pd.DataFrame(data)
print("\nOriginal Data:\n", df)

# Data Cleaning
df_clean = df.dropna()
print("\nAfter Removing Missing Values:\n", df_clean)

# Aggregation
avg_marks = df_clean['Marks'].mean()
print("\nAverage Marks:", avg_marks)

# Grouping
grouped = df_clean.groupby('Age')['Marks'].mean()
print("\nGrouped Data:\n", grouped)